### ISSUE TITLE
Disallowed data tag error due to Datapack-Loader

### ISSUE THREAD

**Issue by Darkiceflame** [Siphalor/nbt-crafting#1]
When attempting to add any recipe with custom data in the result, the following error is returned in the output log:

`Parsing error loading recipe test:example com.google.gson.JsonParseException: Disallowed data tag found at net.minecraft.class_1869.method_8155(class_1869.java:235) at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:90) at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) at net.minecraft.class_1863.method_17720(class_1863.java:139) at net.minecraft.class_1863.method_14491(class_1863.java:61) at net.minecraft.class_4013.method_18235(class_4013.java:12) at net.minecraft.class_4013$$Lambda$1665/363717234.run(Unknown Source) at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at net.minecraft.class_4014.method_18365(class_4014.java:71) at net.minecraft.class_4014$$Lambda$1776/1555348096.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:47) at net.minecraft.class_4014.method_18367(class_4014.java:70) at net.minecraft.class_4014$$Lambda$1662/2107660410.execute(Unknown Source) at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:703) at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at net.minecraft.class_4014.method_18365(class_4014.java:71) at net.minecraft.class_4014$$Lambda$1776/1555348096.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:47) at net.minecraft.class_4014.method_18367(class_4014.java:70) at net.minecraft.class_4014$$Lambda$1662/2107660410.execute(Unknown Source) at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1954) at net.minecraft.class_4014$1.method_18374(class_4014.java:53) at net.minecraft.class_4014$1$$Lambda$1663/1202261290.run(Unknown Source) at net.minecraft.class_3738.run(class_3738.java:18) at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:720) at net.minecraft.class_1255.method_18248(class_1255.java:77) at net.minecraft.server.MinecraftServer.method_18248(MinecraftServer.java:697) at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1451) at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:446) at net.minecraft.class_1132.method_3735(class_1132.java:79) at net.minecraft.class_1132.method_3823(class_1132.java:104) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:607) at java.lang.Thread.run(Thread.java:745)`

Adding custom data to the ingredients works fine. For this instance I used the example script provided on the home page of the wiki.

**Comment by Siphalor** [comment]
Which minecraft version and which version of nbt crafting are you using?

**Comment by Darkiceflame** [comment]
This was done in the 19w09a snapshot using version 1.1.1, single-player. If it makes a difference, I was originally using the datapack loader mod by Pannoniae, but the issue persisted even when all mods (save for this one and Fabric) were removed.

**Comment by Siphalor** [comment]
Can you show me the complete log?

**Comment by Darkiceflame** [comment]
Upon further testing this does seem to be due to an incompatibility with the Datapack Loader mod, as it worked fine when I removed that mod completely. It appears to be an issue on that mod's end, not NBT Crafting's. I'll provide the log just in case.

`[11:32:09] [main/INFO]: [MixinLoader] Loading 4 mods: fabricloader(0.3.7), datapack-loader(1.0.0), fabric(0.2.3), nbtcrafting(1.0.0-beta.0)
[11:32:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/XXXX/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.7.11.16/sponge-mixin-0.7.11.16.jar Service=Knot/Fabric Env=CLIENT
[11:32:09] [main/INFO]: Compatibility level set to JAVA_8
[11:32:11] [main/INFO]: Setting user: Darkiceflame42
[11:32:15] [main/INFO]: [FabricLoader] Loading 4 mods: fabricloader(0.3.7), datapack-loader(1.0.0), fabric(0.2.3), nbtcrafting(1.0.0-beta.0)
[11:32:15] [main/WARN]: Skipping bad option: lastServer:
[11:32:15] [main/WARN]: Skipping bad option: enableVsync:true
[11:32:15] [main/WARN]: Skipping bad option: fullscreen:false
[11:32:15] [main/WARN]: Skipping bad option: maxFps:260
[11:32:15] [main/WARN]: Skipping bad option: forceUnicodeFont:false
[11:32:15] [main/INFO]: LWJGL Version: 3.2.1 build 12
[11:32:19] [main/INFO]: Narrator library for x64 successfully loaded
[11:32:19] [main/ERROR]: Failed to load Realms module
java.lang.NoSuchMethodException: com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen.<init>(net.minecraft.realms.RealmsScreen)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_51]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_51]
	at net.minecraft.realms.RealmsBridge.getNotificationScreen(RealmsBridge.java:45) [?:?]
	at net.minecraft.class_442.method_2224(class_442.java:164) [?:?]
	at net.minecraft.class_437.method_2233(class_437.java:312) [?:?]
	at net.minecraft.class_310.method_1507(class_310.java:830) [?:?]
	at net.minecraft.class_310.method_1503(class_310.java:598) [?:?]
	at net.minecraft.class_310.method_1514(class_310.java:397) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:154) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:347) [fabric-loader-0.3.7.109.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.3.7.109.jar:?]
[11:32:25] [Server-Worker-1/WARN]: Unable to load model: 'minecraft:gui/console_powered' referenced from: minecraft:stick#inventory: java.io.FileNotFoundException: minecraft:models/gui/console_powered.json
[11:32:25] [Server-Worker-1/WARN]: Unable to load model: 'minecraft:gui/console_unpowered' referenced from: minecraft:stick#inventory: java.io.FileNotFoundException: minecraft:models/gui/console_unpowered.json
[11:32:26] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:32:27] [Thread-3/INFO]: Initializing No Sound
[11:32:27] [Thread-3/INFO]: (Silent Mode)
[11:32:27] [main/INFO]: Created: 1024x512 textures-atlas
[11:32:27] [Thread-3/INFO]: OpenAL initialized.
[11:32:27] [Sound Library Loader/INFO]: Preloading sound minecraft:sounds/ambient/underwater/underwater_ambience.ogg
[11:32:27] [Sound Library Loader/INFO]: Sound engine started
[11:32:27] [main/INFO]: Created: 256x256 textures/particle-atlas
[11:32:27] [main/INFO]: Created: 256x256 textures/painting-atlas
[11:32:27] [main/INFO]: Created: 256x128 textures/mob_effect-atlas
[11:33:36] [main/INFO]: Loading Fabric registry [file 1/4]
[11:33:36] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11:33:36] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11:33:36] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[11:33:36] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[11:33:36] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[11:33:36] [Server thread/INFO]: Starting integrated minecraft server version 19w09a
[11:33:36] [Server thread/INFO]: Generating keypair
[11:33:37] [Server thread/INFO]: Loading Fabric registry [file 1/4]
[11:33:37] [Server thread/INFO]: Reloading ResourceManager: Default, Fabric API, NBTCraftingMod
[11:33:37] [Server thread/ERROR]: Parsing error loading recipe test:example
com.google.gson.JsonParseException: Disallowed data tag found
	at net.minecraft.class_1869.method_8155(class_1869.java:235) ~[?:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:90) ~[?:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[?:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:139) ~[?:?]
	at net.minecraft.class_1863.method_14491(class_1863.java:61) [?:?]
	at net.minecraft.class_4013.method_18235(class_4013.java:12) [?:?]
	at net.minecraft.class_4013$$Lambda$1587/818628762.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) [?:?]
	at net.minecraft.class_4014$$Lambda$1691/2118912967.run(Unknown Source) [?:?]
	at net.minecraft.class_1255.execute(class_1255.java:47) [?:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) [?:?]
	at net.minecraft.class_4014$$Lambda$1584/2020015678.execute(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:703) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:635) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) [?:?]
	at net.minecraft.class_4014$$Lambda$1691/2118912967.run(Unknown Source) [?:?]
	at net.minecraft.class_1255.execute(class_1255.java:47) [?:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) [?:?]
	at net.minecraft.class_4014$$Lambda$1584/2020015678.execute(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:653) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1954) [?:1.8.0_51]
	at net.minecraft.class_4014$1.method_18374(class_4014.java:53) [?:?]
	at net.minecraft.class_4014$1$$Lambda$1585/1649464124.run(Unknown Source) [?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) [?:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:720) [?:?]
	at net.minecraft.class_1255.method_18248(class_1255.java:77) [?:?]
	at net.minecraft.server.MinecraftServer.method_18248(MinecraftServer.java:697) [?:?]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1451) [?:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:446) [?:?]
	at net.minecraft.class_1132.method_3735(class_1132.java:79) [?:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:104) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:607) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[11:33:38] [Server thread/INFO]: Loaded 6 recipes
[11:33:40] [Server thread/INFO]: Loaded 800 advancements
[11:33:40] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[11:33:40] [main/INFO]: Preparing spawn area: 0%
[11:33:40] [main/INFO]: Preparing spawn area: 0%
[11:33:41] [main/INFO]: Preparing spawn area: 0%
[11:33:41] [main/INFO]: Preparing spawn area: 0%
[11:33:42] [main/INFO]: Preparing spawn area: 0%
[11:33:42] [main/INFO]: Preparing spawn area: 0%
[11:33:43] [main/INFO]: Preparing spawn area: 21%
[11:33:44] [main/INFO]: Time elapsed: 3917 ms
[11:33:44] [Server thread/INFO]: Changing view distance to 30, from 10
[11:33:45] [Server thread/ERROR]: Tried to load unrecognized recipe: test:dough removed now.
[11:33:45] [Server thread/INFO]: Darkiceflame42[local:E:1b7144a1] logged in with entity id 250 at (-165.0572805717563, 4.0, -65.2909464792526)
[11:33:46] [Server thread/INFO]: Darkiceflame42 joined the game
[11:33:47] [Server thread/INFO]: Saving and pausing game...
[11:33:47] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_nether
[11:33:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:33:47] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_end
[11:33:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:33:47] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:overworld
[11:33:47] [main/INFO]: Loaded 27 advancements
[11:33:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved`

**Comment by Siphalor** [comment]
I don't think it's a datapack-loader bug as this mod doesn't really do anything.
Looks more like a loader or mixin bug.
Sadly this could take some more time to fix.

I'd really love to see both mods together too.

**Comment by Siphalor** [comment]
At last the author od datapack-loader and me did the same mistake resulting in overlapping files :/
Costed me way too much time to find the bug
