### ISSUE TITLE
Opening the Recipe Book GUI causes a crash

### ISSUE THREAD

**Issue by Darkiceflame** [Siphalor/nbt-crafting#3]
**Version**
Snapshot 19w12b, Mod version 1.1.4

**Describe the bug**
If a player with previously enabled recipes attempts to access any GUI with an open recipe book (Survival inventory, crafting table, etc.) the game will crash.

**To Reproduce**
1. Give the player a recipe (Done using /recipe give [Player] \* in testing. The bug doesn't happen if the player has no recipes.)
2. Open any GUI which has a recipe book.
3. Attempt to open the recipe book if it is not already open.

**Expected behavior**
Recipe book can be accessed properly without crashing.

**Log**

```
        java.lang.NoSuchFieldError: field_2069
	at net.minecraft.class_514.handler$drawButton$zcb000(class_514.java:529)
	at net.minecraft.class_514.renderButton(class_514.java:104)
	at net.minecraft.class_339.render(class_339.java:83)
	at net.minecraft.class_513.method_2634(class_513.java:111)
	at net.minecraft.class_507.render(class_507.java:269)
	at net.minecraft.class_479.render(class_479.java:61)
	at net.minecraft.class_757.method_3192(class_757.java:688)
	at net.minecraft.class_310.method_1523(class_310.java:971)
	at net.minecraft.class_310.method_1514(class_310.java:412)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:347)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

```

**Comment by Siphalor** [comment]
It's fixed now.
There was a bit of mapping confusion going on with buttons.

The new realease (1.1.5) should be available soon on curseforge or directly via GitHub
