### ISSUE TITLE
NBT transfer not working properly in 20w09a

### ISSUE THREAD

**Issue by Nathan22211** [Siphalor/nbt-crafting#41]
**Version**
20w09a
2.0.0
**Describe the bug**
the $ in NBT recipes is not allowing NBT from tool to transfer

**To Reproduce**
1. use this JSON `{
	"type": "nbtcrafting:anvil",
	"base": {
		"item": "minecraft:potion",
        "data": {
            "Potion": "minecraft:harming"
        }
	},
	"ingredient": {
		"item": "minecraft:diamond_axe"
	},
	"result": {
		"item": "minecraft:diamond_axe",
        "data": {
            "$": "$ i1",
            "Enchant": [
                "Magic_life1"
            ]
        }
	},
	"levels": 6
}` make sure the axe you use has NBT on it
2. Bug appears

**Expected behavior**
the ax should keep damage and NBT.

**Log**
`de.siphalor.nbtcrafting.dollar.DollarEvaluationException: Could not resolve reference to nbt tag 'i1'
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.dollar.part.unary.ReferenceDollarPart.evaluate(ReferenceDollarPart.java:23)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.dollar.Dollar.apply(Dollar.java:24)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.api.RecipeUtil.lambda$applyDollars$0(RecipeUtil.java:59)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.api.RecipeUtil$$Lambda$4535/64956478.accept(Unknown Source)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.api.RecipeUtil.applyDollars(RecipeUtil.java:57)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at de.siphalor.nbtcrafting.anvil.AnvilRecipe.method_8116(AnvilRecipe.java:74)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1706.handler$zcp000$updateResult(class_1706.java:550)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1706.method_7628(class_1706.java)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1706.method_7625(class_1706.java:438)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_12060(class_3244.java:544)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2855.method_12408(class_2855.java:30)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2855.method_11054(class_2855.java:8)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2600.method_11072(class_2600.java:21)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2600$$Lambda$4020/1855975977.run(Unknown Source)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:144)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:750)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:142)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:118)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:732)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:726)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:127)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:711)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
[04:42:43] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)`

**Additional context**

**Comment by Siphalor** [comment]
`i1` is now called `ingredient`.
See [here](https://mcwiki.siphalor.de/nbt-crafting/v2/#updating/#json-changes) for notes about updating to 2.0.0. 🙂
