### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Shad0wSlam** [Siphalor/nbt-crafting#68]
`[23:42:03] [main/INFO]: Loading for game Minecraft 1.16.5
[23:42:03] [ForkJoinPool-1-worker-11/WARN]: Non-Fabric mod JAR at "C:\Games\Minecraft\Modded Minecraft\Instances\Paracasing\mods\AppleSkin-mc1.16.2-forge-1.0.14.jar", ignoring
[23:42:03] [ForkJoinPool-1-worker-12/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[23:42:03] [ForkJoinPool-1-worker-12/WARN]: Non-Fabric mod JAR at "C:\Games\Minecraft\Modded Minecraft\Instances\Paracasing\mods\vanilladeathchest-1.16.3-1.11.0.8.jar", ignoring
[23:42:03] [ForkJoinPool-1-worker-8/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[23:42:03] [main/INFO]: [FabricLoader] Loading 96 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, logical_zoom@0.0.8, fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.10.184, libcd@3.0.3+1.16.3, fabricloader@0.11.1, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.0.1, fabric-structure-api-v1@1.1.4+ca58154a7d, slimeorigin@1.0.1, org_aperlambda_lambdajcommon@1.8.1, fabric-containers-v0@0.1.11+9354966b7d, pehkui@1.7.1+21w03a, fabric-object-builder-api-v1@1.9.4+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, java@8, impersonate@2.1.0, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, xaeroworldmap@1.12.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.0.1, lambdynlights@1.3.4+1.16, fabric-textures-v0@1.0.6+ca58154a7d, cardinal-components-item@2.7.2, worldeditcui@1.16.5+02, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.0.1, org_jetbrains_kotlin_kotlin-stdlib@1.4.30, litematica@0.0.0-dev.20210120.213004, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.30, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.31.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, cosmetic-armor@1.0.0, fabric-networking-v0@0.3.2+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, roughlyenoughitems-default-plugin@5.10.184, fabric-screen-handler-api-v1@1.1.5+9354966b7d, modmenu@1.16.8, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.1.0+f9b3753b7d, cloth-basic-math@0.5.1, amecsapi@1.1.3+mc1.16.5, fabric-screen-api-v1@1.0.0+c045166c7d, origins-classes@1.1.1, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.30, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, extraorigins@1.16.5-7, roughlyenoughitems-runtime@5.10.184, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, cloth-client-events-v0@1.5.47, blockus@2.1.0+1.16.5, roughlyenoughitems@5.10.184, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, libgui@3.3.2+1.16.4, curios@0.0.11-1.16.4, fabric-language-kotlin@1.4.30+build.2, fabric-entity-events-v1@1.0.3+ca58154a7d, origins@0.5.1, xaerominimap@21.4.0, nbtcrafting@2.0.8+mc20w51a, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, mousewheelie@1.6.4+mc1.16.4, fabric-key-binding-api-v1@1.0.4+9354966b7d, cloth-config2@4.11.14, spruceui@2.0.4+1.16, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, autoconfig1u@3.2.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, malilib@0.10.0-dev.21+arne.2, org_jetbrains_kotlin_kotlin-reflect@1.4.30, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.2+fc3c499, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.7.10, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.7.10, adorn@1.13.0+1.16.5, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d, tweed@3.0.0-beta.22
[23:42:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Shadow/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[23:42:06] [main/WARN]: Error loading class: de/siphalor/nmuk/impl/NMUKKeyBindingHelper (java.lang.ClassNotFoundException: de/siphalor/nmuk/impl/NMUKKeyBindingHelper)
[23:42:06] [main/WARN]: @Mixin target de/siphalor/nmuk/impl/NMUKKeyBindingHelper was not found amecsapi.mixins.json:MixinNMUKKeyBindingHelper
[23:42:06] [main/WARN]: @Mixin target me/shedaniel/rei/server/RecipeFinder is public in nbtcrafting.compat.mixins.json:MixinREIRecipeFinder and should be specified in value
[23:42:08] [main/FATAL]: Mixin apply failed nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> net.minecraft.class_2589: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on beforeCanCraft could not find any targets matching 'Lnet/minecraft/class_2589;method_31665(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2589;)V' in net.minecraft.class_2589. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> Prepare Injections ->  -> handler$zno000$beforeCanCraft(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2589;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeCanCraft could not find any targets matching 'Lnet/minecraft/class_2589;method_31665(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2589;)V' in net.minecraft.class_2589. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> Prepare Injections ->  -> handler$zno000$beforeCanCraft(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2589;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.1.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.class_2246.<clinit>(class_2246.java:360) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$206/1843459456.get(Unknown Source) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_5458$$Lambda$214/801284613.accept(Unknown Source) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]`

Um... yeah, it crashes on startup. Not much more to say unless you need more?

**Comment by Siphalor** [comment]
You're using `nbtcrafting@2.0.8+mc20w51a` which is built for the snapshot 20w51a.
You probably just downloaded the wrong file - choose the one that says [1.16.2+] on it :)
