### ISSUE TITLE
[compatibility] Version Skip?

### ISSUE THREAD

**Issue by fooeyround** [Siphalor/nbt-crafting#73]
**Version**
21w08b mc Mod: Alpha 16 of Version 2.0.0
**Describe the bug**
Is it not working with this version support to happen or is it support to be supported?

**To Reproduce**
use the mod on 21w08b
**Expected behavior**

**Log**
[INFO] Loading for game Minecraft 21w08b

[INFO] [FabricLoader] Loading 50 mods: fabric-renderer-api-v1@0.4.1+92519afa59, fabric-keybindings-v0@0.2.2+36b77c3e59, carpet-autocraftingtable@1.4.17, fabricloader@0.11.3, fabric-structure-api-v1@1.1.6+7268309e59, fabric-containers-v0@0.1.11+524a2e8559, fabric-object-builder-api-v1@1.10.5+40e100eb59, fabric-dimensions-v1@2.0.6+524a2e8559, java@8, fabric-game-rule-api-v1@1.0.6+92519afa59, fabric-api-base@0.2.1+524a2e8559, fabric-rendering-data-attachment-v1@0.1.5+92519afa59, fabric-textures-v0@1.0.6+92519afa59, fabric-rendering-fluids-v1@0.1.13+92519afa59, fabric-blockrenderlayer-v1@1.1.5+92519afa59, fabric-lifecycle-events-v1@1.4.3+40e100eb59, fabric-renderer-registries-v1@3.1.0+2a1dabb659, fabric-loot-tables-v1@1.0.4+92519afa59, carpet-extra@1.4.27, fabric@0.31.1+1.17, carpet@1.4.28, fabric-particles-v1@0.2.4+92519afa59, fabric-networking-v0@0.3.2+92519afa59, fabric-networking-blockentity-v0@0.2.9+40e100eb59, minecraft@1.17-alpha.21.8.b, fabric-screen-handler-api-v1@1.1.6+40e100eb59, fabric-command-api-v1@1.1.0+f9d6353a59, fabric-screen-api-v1@1.0.0+e568618059, fabric-tool-attribute-api-v1@1.2.9+36b77c3e59, fabric-renderer-indigo@0.4.6+92519afa59, fabric-item-api-v1@1.2.3+36b77c3e59, fabric-events-interaction-v0@0.4.5+7268309e59, fabric-crash-report-info-v1@0.1.3+92519afa59, fabric-entity-events-v1@1.0.3+92519afa59, nbtcrafting@2.0.0-alpha.16+1.15.2, fabric-rendering-v0@1.1.2+92519afa59, fabric-key-binding-api-v1@1.0.4+524a2e8559, fabric-rendering-v1@1.5.1+92519afa59, fabric-resource-loader-v0@0.4.4+1eb2670e59, fabric-content-registries-v0@0.2.1+92519afa59, fabric-tag-extensions-v0@1.1.2+92519afa59, fabric-biome-api-v1@3.1.4+1eb2670e59, fabric-registry-sync-v0@0.7.5+92519afa59, fabric-commands-v0@0.2.2+92519afa59, fabric-mining-levels-v0@0.1.3+92519afa59, fabric-networking-api-v1@1.0.5+7268309e59, fabric-events-lifecycle-v0@0.2.1+92519afa59, fabric-models-v0@0.2.1+92519afa59, fabric-item-groups-v0@0.2.3+92519afa59, fabric-object-builders-v0@0.7.3+92519afa59

[INFO] SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/gs-41640/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER

[WARNING] Error loading class: me/shedaniel/rei/server/RecipeFinder (java.lang.ClassNotFoundException: me/shedaniel/rei/server/RecipeFinder)

[WARNING] @Mixin target me.shedaniel.rei.server.RecipeFinder was not found nbtcrafting.compat.mixins.json:MixinREIRecipeFinder

[main/FATAL]: Mixin apply failed nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> net.minecraft.class_2589: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on canCraft could not find any targets matching 'Lnet/minecraft/class_2589;method_11027()Z' in net.minecraft.class_2589. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> Prepare Injections -> -> handler$zbm000$canCraft(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]

org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on canCraft could not find any targets matching 'Lnet/minecraft/class_2589;method_11027()Z' in net.minecraft.class_2589. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> Prepare Injections -> -> handler$zbm000$canCraft(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[fabric-server-launch.jar:?]

at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source) ~[?:?]

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]

at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]

at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]

at net.minecraft.class_2246.<clinit>(class_2246.java:376) ~[intermediary-mcserver.jar:?]

at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-mcserver.jar:?]

at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-mcserver.jar:?]

at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-mcserver.jar:?]

at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-mcserver.jar:?]

at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_212]

at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-mcserver.jar:?]

at net.minecraft.class_2378.<clinit>(class_2378.java:259) [intermediary-mcserver.jar:?]

at carpet_autocraftingtable.CraftingTableBlockEntity.<clinit>(CraftingTableBlockEntity.java:36) [carpet-autocraftingtable-20w46a-1.4.17.jar:?]

at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:11) [carpet-autocraftingtable-20w46a-1.4.17.jar:?]

at net.minecraft.class_128.handler$zdf000$gameStarted(class_128.java:516) [intermediary-mcserver.jar:?]

at net.minecraft.class_128.method_24305(class_128.java) [intermediary-mcserver.jar:?]

at net.minecraft.server.Main.main(Main.java:87) [intermediary-mcserver.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!

at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!

at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)

at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)

Caused by: java.lang.RuntimeException: An exception occurred when launching the server!

at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)

at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)

... 1 more

Caused by: java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)

... 2 more

Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)

at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)

at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)

... 7 more

Caused by: java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)

... 9 more

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)

at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at net.minecraft.class_2246.<clinit>(class_2246.java:376)

at net.minecraft.class_3523.<clinit>(class_3523.java:13)

at net.minecraft.class_5471.<clinit>(class_5471.java:11)

at net.minecraft.class_5458.method_30573(class_5458.java:44)

at net.minecraft.class_5458.method_30566(class_5458.java:75)

at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

at net.minecraft.class_5458.<clinit>(class_5458.java:74)

at net.minecraft.class_2378.<clinit>(class_2378.java:259)

at carpet_autocraftingtable.CraftingTableBlockEntity.<clinit>(CraftingTableBlockEntity.java:36)

at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:11)

at net.minecraft.class_128.handler$zdf000$gameStarted(class_128.java:516)

at net.minecraft.class_128.method_24305(class_128.java)

at net.minecraft.server.Main.main(Main.java:87)

... 14 more

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity] from phase [DEFAULT] in config [nbtcrafting.mixins.json] FAILED during APPLY

at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)

... 33 more

Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on canCraft could not find any targets matching 'Lnet/minecraft/class_2589;method_11027()Z' in net.minecraft.class_2589. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:brewing.MixinBrewingStandBlockEntity -> Prepare Injections -> -> handler$zbm000$canCraft(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)

at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)

at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)

at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)

at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)

... 33 more

**Comment by Siphalor** [comment]
You're using the completely wrong version of Nbt Crafting (`2.0.0-alpha.16+1.15.2`). As the version you downloaded clearly states it is meant to be used on Minecraft 1.15.2.
It's also impressively outdated as the current version is `2.0.11`!

Since you want to play on 21w08a the current version for 21w15a is probably not going to work.
You're best chance is to try the version for 20w49a and later: [[20w49a+] 2.0.8](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting/files/3225242).
