### ISSUE TITLE
[bug] 1.17 Server Crashes When Any Item Is Placed In A Crafting Table

### ISSUE THREAD

**Issue by ZombieNW** [Siphalor/nbt-crafting#78]
**Version**
Mod Version: [1.17-pre1+] 2.0.15
MC Version: 1.17
**Describe the bug**
Any time an item is placed in the crafting table when trying to craft something, the server instantly crashes.

**To Reproduce**
1. Try to craft something on a 1.17 server.
2. Bug appears

**Expected behavior**
Server not crashing.

**Log**
The important parts of the log.
`
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/9/21, 12:42 PM
Description: Exception in server tick loop

com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: class net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a tried to access private field net.minecraft.class_1662.id2StackMap (net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a and net.minecraft.class_1662 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e), (Type net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a (loader: net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e) is not a nest member of type net.minecraft.class_1662 (loader: net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e): current type is not listed as a nest member)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at net.minecraft.class_1662.method_7408(class_1662.java:611)
	at net.minecraft.class_1662.method_20478(class_1662.java:37)
	at net.minecraft.class_1867.method_17730(class_1867.java:62)
	at net.minecraft.class_1867.method_8115(class_1867.java:15)
	at net.minecraft.class_3956.method_17725(class_3956.java:30)
	at net.minecraft.class_1863.method_17718(class_1863.java:70)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.tryAdvance(CollectSpliterators.java:60)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at net.minecraft.class_1863.method_8132(class_1863.java:70)
	at net.minecraft.class_1714.method_17399(class_1714.java:66)
	at net.minecraft.class_1714.method_17401(class_1714.java:81)
	at net.minecraft.class_3914.method_17394(class_3914.java:35)
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
	at net.minecraft.class_3914.method_17393(class_3914.java:34)
	at net.minecraft.class_1714.method_7609(class_1714.java:81)
	at net.minecraft.class_1715.method_5447(class_1715.java:63)
	at net.minecraft.class_1735.method_7673(class_1735.java:61)
	at net.minecraft.class_1735.method_32755(class_1735.java:143)
	at net.minecraft.class_1703.method_30010(class_1703.java:379)
	at net.minecraft.class_1703.method_7593(class_1703.java:258)
	at net.minecraft.class_3244.method_12076(class_3244.java:1404)
	at net.minecraft.class_2813.method_12191(class_2813.java:50)
	at net.minecraft.class_2813.method_11054(class_2813.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744)
	at net.minecraft.server.MinecraftServer.handler$zmc000$modifiedRunLoop(MinecraftServer.java:3902)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalAccessError: class net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a tried to access private field net.minecraft.class_1662.id2StackMap (net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a and net.minecraft.class_1662 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e), (Type net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a (loader: net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e) is not a nest member of type net.minecraft.class_1662 (loader: net.fabricmc.loader.launch.knot.KnotClassLoader @268f106e): current type is not listed as a nest member)
	at net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a.load(MixinRecipeFinder.java:68)
	at net.minecraft.class_1662$Anonymous$dfe26c5e9fee4ffd9ed8d6c6c152c52a.load(MixinRecipeFinder.java:65)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 49 more
`

**Comment by Siphalor** [comment]
This is likely caused by SpongePowered/Mixin#495.
I'm gonna work around this by not using anonymous classes in that mixin anymore.
